mydict={'HOW I MET YOUR MOTHER': 3, 'THE SOPRANOS': 1, 'FRIDAY NIGHT LIGHTS': 1, 'FAMILY GUY': 2, 'NEW GIRL': 4, 'FRIENDS': 9, 'OFFICE': 2, 'BREAKING BAD': 5, 'MODERN FAMILY': 3, 'WHITE COLLAR': 2, 'GAME OF THRONES': 6, 'THE UNTAMED': 1, 'THE 100': 1, 'THE OFFICE': 13, 'AVATAR: THE LAST AIRBENDER': 3, 'COBRA KAI': 1, 'SHERLOCK HOMES': 1, 'ARROW': 1, 'GRACE AND FRANKIE': 1, 'THE GREAT BRITISH BAKING SHOW': 1, 'THE MENTALIST': 1, 'BROOKLYN-99': 1, 'AVATAR THE LAST AIRBENDER': 5, 'PARKS AND REC': 2, 'ARCHER': 1, 'THE SIMPSONS': 2, 'THE FLASH': 2, 'STRANGER THINGS': 2, 'SQUID GAME': 3, 'COMMUNITY': 8, 'CURB YOUR ENTHUSIASM': 1, 'HANNAH MONTANA': 1, 'THE GOOD PLACE': 4, 'BAND OF BROTHERS': 1, 'JEOPARDY': 1, 'VIOLET EVERGARDEN': 1, 'CRIMINAL MINDS': 2, 'SHARK TANK': 1, 'STAR TREK: THE NEXT GENERATION': 1, 'PARKS AND RECREATION': 1, 'MAD MEN': 1, 'SOUTH PARK': 1, 'NORSEMEN': 1, 'THE WEST WING': 1, 'REGULAR SHOW': 1, 'TED LASSO': 1, 'THE WIRE': 1, 'LOST': 1, 'QUEENÂ€™S GAMBIT': 1, 'SIX FLYING DRAGONS': 2, 'GILMORE GIRLS': 2, 'REBA': 1, 'EVACUATE EARTH': 1, 'SUPERNATURAL': 1, 'PEAKY BLINDERS': 1, 'YOU': 1, "GREY'S ANATOMY": 2, 'THE CROWN': 2, 'ARRESTED DEVELOPMENT': 1, 'BLACK MIRROR': 1, 'SATURDAY NIGHT LIVE': 1, 'THE BACHELORETTE': 1, 'LAW AND ORDER': 1, 'B99': 1, 'GOT': 1, 'SHERLOCK': 1, 'WANDAVISION': 2, 'ADVENTURE TIME': 1, 'YELLOWSTONE': 1, 'BROOKLYN 99': 2, 'THE HAUNTING OF HILL HOUSE': 1, 'AVATAR': 1, 'THE ORIGINALS': 1, 'LAST WEEK TONIGHT WITH JOHN OLIVER': 1, 'BILLIONS': 1, 'TOP GEAR': 1, 'NEW AMSTERDAM': 1, 'BLUE MOUNTAIN STATE': 1, 'ITS ALWAYS SUNNY IN PHILIDELPHIA': 1, 'THEVOFFICE': 1, 'ATLANTA': 1, 'GOOD OMENS': 1, 'THE BIG BANG THEORY': 1, 'HUNTER X HUNTER': 1, 'SHERLOCK HOLMES': 1, 'ANNE WITH AN E': 1, 'MONEY HEIST': 1, 'SUCCESSION': 1, 'SILICON VALLEY': 1}



def get_key(val):
    for key, value in mydict.items():
         if val == value:
             return key
 
    return "key doesn't exist"
 
 
for a in sorted(mydict.values(),reverse=True):
    print(get_key(a),a)
